EMBERLYN_CATACOMB_ROOMS = {
    (4, 2): {
        "key": "|xEmberlyn Catacomb - Gloomlit Cave|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This cavernous chamber feels less like a natural cave and more like a forgotten burial ground, its walls carved from ancient stone, rough and cracked with age. Flickering lights hover in the air like the restless spirits of the dead, casting an otherworldly glow that illuminates the uneven floor scattered with rubble and bone-like stones. The air is thick and damp, heavy with the scent of decay and old earth. In the shadows, remnants of crumbling tombstones jut out from the ground, their inscriptions long worn away. Deep within, the passage fades into impenetrable darkness, hinting at further depths where the dead may rest undisturbed.",
        "senses": {
            "feel": "The air is damp and cold, and the ground is uneven beneath your feet, strewn with stone fragments and rough soil.",
            "smell": "A musty scent of decay fills the air, mingling with the damp, earthy aroma of ancient stone.",
            "sound": "Faint whispers echo through the chamber, though no source can be found, mingling with the soft drip of moisture seeping through the stone.",
            "taste": "The air is thick and metallic, a faint tang of iron lingering on your tongue.",
        },
        "details": {
            "flickering lights": "Pale, golden lights hover near the walls, seeming to float like will-o'-wisps, casting eerie shadows that dance across the chamber.",
            "tombstones": "Weathered, broken tombstones protrude from the ground at odd angles, their inscriptions faded and obscured by layers of grime and time.",
            "rubble": "Chunks of stone and debris litter the floor, scattered like bones left to rest in this forgotten crypt, adding a sense of neglect and abandonment.",
        },
    },
    (4, 3): {
        "key": "|xEmberlyn Catacomb - Forgotten Crypt|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This cavernous space feels like a sanctum for the forsaken dead, its stone walls enclosing an air thick with dust and sorrow. Candles are scattered across ledges and crevices, their soft, flickering flames casting elongated shadows that dance across the rough-hewn stone. Weathered boards, broken as if by some past upheaval, lie scattered on the floor, along with remnants of shattered crates and decayed belongings. Stalactites hang from the ceiling like the teeth of some ancient beast, adding to the oppressive stillness of the crypt. Amid the cluttered floor, tiny stalagmites jut upward, like the bony fingers of forgotten souls reaching for the surface.",
        "senses": {
            "feel": "A heavy stillness fills the air, thick and unmoving, with a damp chill that clings to your skin.",
            "smell": "A pungent mixture of wax, dust, and ancient decay lingers in the air, sharp and earthy.",
            "sound": "The silence is deep, broken only by the occasional drip of water from above, echoing softly in the vast space.",
            "taste": "A faint bitterness coats your tongue, mingled with the sharp, mineral tang of stone and damp air.",
        },
        "details": {
            "candles": "Dozens of candles, their wax pooling and dripping, rest in various cracks and crevices along the walls, their faint light barely illuminating the depths of the crypt.",
            "statue": "The hooded statue stands solemnly in the corner, its face obscured and details weathered, its outstretched hand a silent gesture of warning or invitation.",
            "broken boards": "Splintered boards and broken crates are strewn haphazardly on the ground, remnants of some long-forgotten disturbance, now lying in disrepair and neglect.",
        },
    },
    (4, 4): {
        "key": "|xEmberlyn Catacomb - Forgotten Crypt|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This shadowed chamber bears the marks of recent violence and desecration. Fragments of broken wood and twisted metal are strewn across the rough stone floor, mingled with shattered bones that crunch underfoot. The air is thick with the scent of stale blood and damp earth, and a faint crimson stain is smeared across the floor, trailing off into the darkness. The walls are scarred and gouged, as if clawed at by desperate hands or the weapons of intruders. Dim candlelight from the adjacent chambers barely pierces the gloom here, casting flickering shadows that make the walls seem to pulse and breathe. In the far corners, shattered crates and abandoned tools lie forgotten.",
        "senses": {
            "feel": "The air is cold and oppressive, carrying a sense of lingering dread and hostility.",
            "smell": "The scent of stale blood mingles with the earthy dampness of stone and rot.",
            "sound": "An unsettling silence fills the room, broken only by the occasional drip of moisture seeping from the ceiling.",
            "taste": "A faint metallic tang of blood lingers in the air, clinging to the back of your throat.",
        },
        "details": {
            "crimson stains": "Dark, drying stains streak across the floor, evidence of a recent struggle or ritual, their deep color stark against the dull stone.",
            "shattered bones": "Splintered bones lie scattered amidst the debris, their brittle white surfaces catching the faint light, hinting at the age and abandonment of this place.",
            "scarred walls": "The walls are marred with scratches and gouges, each one a silent record of past conflicts or frantic attempts to escape the vault's confines.",
        },
    },
    (4, 5): {
        "key": "|#4B392EEmberlyn Catacomb - Shadowed Ossuary|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "The walls of this shadowed chamber loom high and close, rough and uneven, like the inside of an ancient tomb hewn by unseen hands. Scattered across the dusty floor are remnants of wooden crates and broken tools, discarded and rotting with age. Flickering candles cast trembling halos of light that only deepen the gloom around them. The room is filled with a stifling stillness, as if holding its breath, the silence broken only by the occasional drip of water seeping through the stone. Jagged bones poke out from the earth in unsettling angles, half-buried in the dirt, as though the ground itself was disturbed in some past upheaval. In the dim light, the rough textures of the walls take on strange shapes, like faces carved by shadows into the rock.",
        "senses": {
            "feel": "The air is heavy and oppressive, with a damp chill that clings to your skin.",
            "smell": "A sharp, earthy scent of decay fills the room, mixed with the faint waxy aroma of melted candle wax.",
            "sound": "The silence is thick and absolute, punctuated only by the occasional soft crackle of candle flames and the distant drip of water.",
            "taste": "The air has a faintly bitter taste, metallic and stale, leaving a lingering sensation on your tongue.",
        },
        "details": {
            "candles": "The candles, scattered along ledges and crates, burn low and flicker weakly, their faint light casting unsettling, elongated shadows against the rock.",
            "broken crates": "Old crates lie in various states of decay, their wood splintered and rotting, half-swallowed by the earth, hinting at a time when this room saw activity now long forgotten.",
            "bones": "Jagged bones protrude from the floor at odd angles, their brittle surfaces gray with age, as if the earth has reluctantly surrendered them from its depths.",
        },
    },
    (4, 6): {
        "key": "|#4C6651Emberlyn Catacomb - Overgrown Sanctuary|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This vast chamber opens up into a breathtaking, verdant sanctuary, hidden away from the world above. Thick curtains of vines drape down from a natural stone arch overhead, their tendrils reaching toward the mist that cloaks the ground below. Shafts of pale, diffused light break through cracks in the ceiling, casting an ethereal glow over the dense undergrowth that flourishes in defiance of the chamber's somber quiet. The ground is soft, carpeted with wild grasses and ferns that sway gently in the still air. Ancient gravestones, half-buried and smothered by creeping ivy, poke through the foliage, their inscriptions worn smooth by time. Far above, a figure watches from a high ledge, obscured by mist, an ever-present sentinel over the sanctuary's silent dead.",
        "senses": {
            "feel": "The air is cool and moist, carrying a soothing calm that feels almost otherworldly in its tranquility.",
            "smell": "A fresh, earthy scent fills the air, mingling with hints of moss and damp stone.",
            "sound": "The faint rustle of leaves is punctuated by occasional drips of water from above, each sound magnified in the hush of the cavern.",
            "taste": "A crisp, clean taste lingers in the air, carrying the faintest trace of minerals and fresh greenery.",
        },
        "details": {
            "vines": "Thick green vines cascade down from above, their leaves glossy and vibrant, creating a curtain of greenery that gives the chamber a cloistered, sacred feel.",
            "gravestones": "The gravestones are ancient and weathered, their once-sharp edges softened by moss and time, with ivy winding around them like the protective embrace of nature.",
            "mist": "The mist hangs low, a silvery haze that blankets the ground, swirling softly around your feet as you move, concealing what may lie beneath.",
        },
    },
    (4, 7): {
        "key": "|#5A4A3BEmberlyn Catacomb - The Stalactite Chamber|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This cavern opens into a wide, solemn chamber, its ceiling hung with rows of sharp stalactites that resemble the fangs of some colossal, slumbering beast. The walls are rugged and rough, colored in warm hues of earth and iron, with veins of darker minerals coursing through the stone like silent, petrified rivers. Flickering candles rest on low stone ledges, their soft glow barely illuminating the shadowed recesses of the chamber. Scattered boulders lie like unmarked graves along the perimeter, each one worn and chipped, as if hiding the memories of ages past. The air here feels heavy, thick with the weight of silence and the lingering scent of damp stone, as though the cave itself were holding its breath.",
        "senses": {
            "feel": "The air is dense and cool, pressing against your skin with an almost suffocating weight.",
            "smell": "A faint, mineral-rich scent fills the room, mingling with the earthy odor of ancient, damp rock.",
            "sound": "The chamber is utterly silent save for the occasional drip of water from above, each drop echoing like a heartbeat.",
            "taste": "The air leaves a gritty taste on your tongue, metallic and earthy, as if the walls themselves exude a sense of age.",
        },
        "details": {
            "stalactites": "The stalactites hang like daggers from the ceiling, each one sharp and pointed, adding an air of menace to the otherwise still chamber.",
            "boulders": "The scattered boulders around the chamber's edge seem placed intentionally, each one worn smooth with time and marked by faint, natural carvings etched by water and erosion.",
            "candlelight": "Small candles flicker from the ledges, their light soft and trembling, casting long shadows that make the chamber seem to shift and breathe in the dim glow.",
        },
    },
    (3, 7): {
        "key": "|#6A523AEmberlyn Catacomb - Forgotten Encampment|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "Nestled within the depths of the cavern, this makeshift encampment exudes an air of abandonment and quiet desperation. A simple wooden tripod suspends an iron brazier filled with embers that cast a dim, flickering glow across the chamber. The walls, rough and jagged, reflect the warm but unsteady light, creating dancing shadows that seem to take on ghostly shapes. Around the fire, scattered stools and broken crates sit in disarray, as if left by weary souls who once sought refuge here. Barrels and sacks line the edges, partially covered in dust, untouched for what seems like ages. The earthy, burnt aroma of the fire mixes with the musty scent of the cavern, giving the room an unsettling sense of life once lived and hastily forgotten.",
        "senses": {
            "feel": "The warmth from the brazier reaches you faintly, mingling with the damp chill of the cavern air.",
            "smell": "A smoky, earthy scent fills the air, mingled with the stale odor of old wood and fabric.",
            "sound": "The quiet crackling of embers punctuates the silence, filling the cavern with a faint, comforting warmth.",
            "taste": "The air tastes faintly of ash, with a bitter edge that lingers on your tongue.",
        },
        "details": {
            "brazier": "The iron brazier, suspended from a wooden tripod, glows with fading embers, casting a soft, orange light across the surroundings, its warmth only barely cutting through the chill of the cavern.",
            "crates and stools": "The stools and crates around the fire are battered and worn, showing signs of age and decay, as if they've been left untouched for many seasons.",
            "barrels and sacks": "Dust-covered barrels and sagging sacks line the walls, their contents unknown, likely forgotten relics of past occupants who once called this place their temporary shelter.",
        },
    },
    (2, 7): {
        "key": "|#3E6248Emberlyn Catacomb - Verdant Rift|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This narrow path winds precariously along a jagged cliff face within the cavern, where nature has stubbornly reclaimed its hold. Lush green moss blankets the ground, glowing faintly under the light that filters in from unseen cracks above, giving the entire area an ethereal, otherworldly illumination. Yellow wildflowers bloom defiantly at the edge of the cliff, their petals delicate against the stark stone. Ivy cascades down the walls in thick, hanging curtains, framing the passage with a living tapestry. Stalactites hang like teeth from the ceiling, dripping water that feeds the moss below, their steady rhythm the only sound breaking the stillness. Ahead, the path narrows further, disappearing into shadow, as if leading deeper into the hidden secrets of the cavern.",
        "senses": {
            "feel": "The air is cool and damp, with a slight breeze that carries the freshness of moss and wet stone.",
            "smell": "A rich, earthy scent fills the air, mingled with the subtle fragrance of wildflowers and fresh greenery.",
            "sound": "The steady drip of water echoes softly, blending with the rustle of leaves and vines shifting in the faint draft.",
            "taste": "The air tastes fresh and mineral-rich, with a slight tang of moss and earthy stone.",
        },
        "details": {
            "moss": "The ground is carpeted with thick, vibrant moss that glows faintly in the dim light, its texture soft underfoot and rich with moisture.",
            "wildflowers": "Delicate yellow wildflowers grow at the edge of the cliff, their fragile beauty contrasting with the rugged stone around them.",
            "ivy": "Long strands of ivy cascade down the walls, their leaves a deep, lush green, adding a sense of life and hidden beauty to the otherwise stark cavern.",
        },
    },
    (1, 7): {
        "key": "|#36494EEmberlyn Catacomb - Grotto|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This secluded chamber is shrouded in shadow, with only faint, ambient light filtering in from unseen cracks above. The ground is uneven, covered in scattered stones and patches of gravel, worn smooth by time and the occasional drip of water from stalactites that hang like spectral fingers from the ceiling. Tall stalagmites rise like ancient monuments from the floor, their jagged forms casting eerie, elongated shadows across the chamber. The walls are rugged and damp, their dark stone surfaces mottled with patches of moss and mineral deposits that glisten faintly in the gloom. In the stillness, the chamber feels untouched and undisturbed, as though time itself has forgotten this silent grotto, preserving it as a resting place for shadows and memories.",
        "senses": {
            "feel": "The air is thick and cool, with a faint dampness that clings to your skin and clothing.",
            "smell": "A heavy, earthy scent fills the space, mingled with the faint tang of minerals and wet stone.",
            "sound": "Silence pervades the chamber, broken only by the slow, rhythmic drip of water echoing in the shadows.",
            "taste": "The air carries a subtle mineral taste, damp and slightly metallic, like stone weathered by centuries of stillness.",
        },
        "details": {
            "stalagmites": "The stalagmites rise from the floor like silent guardians, each one unique in shape and worn smooth by countless years of slow growth.",
            "moss patches": "Small patches of moss cling to the walls, their green muted and dark in the low light, adding a touch of life to the otherwise still chamber.",
            "gravel and stones": "The ground is uneven, littered with small stones and patches of gravel, each piece weathered and smooth, blending into the muted tones of the chamber's floor.",
        },
    },
    (0, 7): {
        "key": "|#2E5C4BEmberlyn Catacomb - Veiled Grove|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This secluded cavern opens into a mist-laden grove, where soft, diffused light seeps through the stone and illuminates dense patches of vibrant greenery. Dew-covered ferns and low bushes spread across the ground, their leaves shimmering faintly in the dim light, adding an eerie tranquility to the space. Moss carpets the stones and creeps up the walls, while long strands of ivy hang from the ceiling, framing the grove like a hidden sanctuary. The air is thick with mist, and a soft, ethereal glow seems to emanate from the foliage itself. In the silence, it feels as though this grove guards ancient secrets, untouched by the outside world.",
        "senses": {
            "feel": "The air is cool and damp, clinging to your skin with a sense of heavy, almost sacred stillness.",
            "smell": "A rich scent of wet earth and greenery fills the air, mingled with the faintest hint of something floral.",
            "sound": "The quiet murmur of trickling water echoes faintly, blending with the whisper of leaves shifting in the gentle draft.",
            "taste": "The air tastes fresh and earthy, carrying the distinct flavor of moss and damp stone.",
        },
        "details": {
            "ferns and bushes": "The ferns and bushes are thick and healthy, their leaves bright and glistening with droplets of moisture that catch the light, creating a subtle shimmer in the mist.",
            "ivy": "Long strands of ivy hang from the ceiling, swaying gently, their tendrils thick and strong, as if woven into the very fabric of the cave.",
            "mist": "The mist hangs low and dense, softening the edges of the grove and casting an ethereal glow, giving the space a dreamlike, almost otherworldly quality.",
        },
    },
    (0, 6): {
        "key": "|#5D4934Emberlyn Catacomb - Embered Shrine|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This secluded chamber bears the quiet reverence of a shrine long forgotten, carved into the rugged heart of the stone. Small candles, their flames low and flickering, are arranged in a rough circle on the uneven floor, casting a faint orange glow that illuminates the immediate area but leaves the rest in shadow. The walls, dark and rough-hewn, absorb the light, making the chamber feel enclosed, as if it were holding its secrets close. Stones are piled haphazardly in the center, forming a crude altar, with smaller rocks scattered across the ground like discarded offerings. The ceiling looms high above, and from it hang jagged stalactites that point down like silent observers over this humble, ember-lit shrine.",
        "senses": {
            "feel": "The air is thick and still, with a slight warmth radiating from the scattered candles.",
            "smell": "A faint, earthy scent lingers in the air, mingled with the waxy aroma of burning candles.",
            "sound": "The gentle crackling of candle flames fills the silence, their quiet warmth seeming to pulse softly in the still air.",
            "taste": "The air is slightly bitter, carrying the taste of damp stone and faint traces of smoke.",
        },
        "details": {
            "candles": "Small, stubby candles flicker softly around the altar, their wax pooling at the base, each flame barely illuminating the stones around it.",
            "altar stones": "The stones piled in the center form a crude, makeshift altar, their rough surfaces worn with time, as though touched by many hands in ages past.",
            "stalactites": "Jagged stalactites hang from the ceiling like teeth, their pointed forms casting long shadows over the shrine, giving the space an air of quiet, solemn reverence.",
        },
    },
    (0, 5): {
        "key": "|xEmberlyn Catacomb - Shadowed Path|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This narrow corridor winds deeper into the earth, its walls cloaked in darkness that presses close on all sides. The floor is uneven, strewn with loose stones that crunch softly underfoot, each step echoing faintly in the silent depths. The air is thick with a musty dampness, and the faint glow of a single distant flame flickers ahead, barely illuminating a rough stone alcove. In the alcove, a weathered statue stands, half-shrouded in shadow, its gaze cast downward as if in silent prayer. The flame beside it dances with an unsteady light, casting long shadows that ripple across the walls, giving the impression of unseen spirits shifting in the gloom.",
        "senses": {
            "feel": "The air is cold and dense, with a slight chill that clings to your skin as you move deeper into the shadows.",
            "smell": "A damp, earthy scent fills the passageway, mingling with the faint smell of candle wax and old stone.",
            "sound": "The silence is profound, broken only by the soft crunch of gravel underfoot and the occasional flicker of the flame.",
            "taste": "The air carries a faint metallic taste, with hints of damp stone and dust.",
        },
        "details": {
            "statue": "The statue stands in a rough alcove, its features worn smooth by time, its posture solemn and reverent, as though bearing witness to the ages.",
            "candle flame": "A lone candle burns beside the statue, its flame small and wavering, casting an uneven glow that barely pierces the surrounding darkness.",
            "stone floor": "The stone floor is rough and uneven, littered with small rocks and debris, each step stirring up a faint echo in the stillness.",
        },
    },
    (0, 4): {
        "key": "|#3A5368Emberlyn Catacomb - Sunken Chamber|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This vast, flooded chamber stretches out before you, its stone walls gleaming with dampness and veiled in shadow. Stalactites hang from the ceiling like silent watchers, their long, pointed forms dripping slowly into the dark water below. The ground is submerged, with cold, ankle-deep water rippling around scattered remnants of stonework - broken slabs and shattered pillars - submerged relics of a catacomb now claimed by the encroaching water. Ivy and moss trail down the walls, and a faint, spectral glow filters through a distant opening, illuminating the far end of the chamber in ghostly light. The atmosphere is dense and oppressive, each step disturbing the silent waters as though awakening ancient memories hidden within the depths.",
        "senses": {
            "feel": "The water is icy and numbing against your skin, while the air is thick and heavy with moisture.",
            "smell": "A faint, stale scent of wet stone and algae fills the chamber, mingled with the earthy smell of decay.",
            "sound": "Soft splashes echo through the chamber with each step, accompanied by the steady drip of water from the stalactites above.",
            "taste": "The air tastes mineral-rich and metallic, leaving a faintly bitter sensation on your tongue.",
        },
        "details": {
            "stalactites": "The stalactites hang in clusters, their sharp tips glistening with droplets that fall into the water below, each one adding a slow, rhythmic pulse to the chamber's silence.",
            "submerged stonework": "Broken pillars and slabs lie scattered and half-submerged, their edges smoothed by the relentless touch of water, remnants of a forgotten structure now lost to the depths.",
            "distant light": "A soft, eerie light filters from an unseen opening, casting a pale glow over the far side of the chamber, its source unknown and unreachable, as if beckoning from another world.",
        },
    },
    (0, 3): {
        "key": "|CEmberlyn Catacomb - Forgotten Mausoleum|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "Emerging from the shadows, the silhouette of a grand mausoleum looms ahead, its stone facade partially bathed in a pale, ghostly light that seeps through unseen cracks in the cavern walls. Tall statues flank the structure's entrance, their expressions solemn and their hands folded as if in eternal prayer, guardians to a tomb untouched by time. A wide staircase leads upward to the arched doorway, its steps worn and uneven from centuries of passage. Stalactites hang from the cavern ceiling like daggers, framing the mausoleum in an ominous embrace. The walls are etched with faint carvings, their details lost to age, but the aura of reverence remains palpable, as though the souls interred here are aware of your presence.",
        "senses": {
            "feel": "A profound stillness fills the air, broken only by a faint, reverent chill that seeps into your bones.",
            "smell": "The scent of ancient stone and dust fills the chamber, with a faint, almost floral undertone that lingers like a memory.",
            "sound": "Silence reigns, amplifying the quiet drip of water from above and the soft, echoing resonance of your own footsteps.",
            "taste": "The air is cool and metallic, with a faint tang of limestone and the taste of stale, aged air.",
        },
        "details": {
            "statues": "The statues are worn but majestic, their faces faded by time, yet their forms radiate a quiet strength, as though eternally vigilant over those entombed within.",
            "carvings": "Barely visible in the dim light, the ancient carvings depict scenes of mourning and passage, their edges softened by centuries, lending them a dreamlike quality.",
            "stairs": "The stone steps leading up to the mausoleum are uneven, some crumbling, marked by the slow, relentless decay of time, yet they hold a quiet dignity in their approach to the resting place beyond.",
        },
    },
    (0, 2): {
        "key": "|#4A4A4AEmberlyn Catacomb - Crypt|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This chamber, carved from cold, gray stone, exudes a sense of silent reverence and age. Thick cobwebs drape over broken relics and forgotten offerings scattered across the dusty floor. Stone columns stand against the walls, their surfaces cracked and scarred, bearing witness to centuries of solitude. A rough-hewn altar lies in the corner, barely illuminated by the dim glow of a few dwindling candles, their wax pooled and hardened from ages of undisturbed burning. The air is thick with the scent of dust and old stone, and every small sound is amplified, creating an echo that fills the room, as if the walls themselves are haunted by faint memories.",
        "senses": {
            "feel": "The air is cold and dry, with a faint weight that presses down on you in the quiet.",
            "smell": "A stale, earthy scent lingers in the air, mixed with the faint, waxy aroma of long-extinguished candles.",
            "sound": "Every sound, even the faintest movement, echoes throughout the chamber, creating a hollow, reverberating silence.",
            "taste": "The air has a chalky taste, dry and slightly metallic, clinging to the back of your throat.",
        },
        "details": {
            "cobwebs": "Thick, dusty cobwebs stretch across the altar and nearby relics, their strands twisted and tangled, like the forgotten threads of an ancient past.",
            "altar": "The stone altar is rough and unadorned, its surface cracked and coated in dust, with faint traces of offerings left in the far corners, long forgotten by the living.",
            "stone columns": "The columns, old and crumbling, stand like silent sentinels in the shadows, their surfaces marked with lines and chips, adding to the crypt's aura of decay and abandonment.",
        },
    },
    (0, 1): {
        "key": "|CEmberlyn Catacomb - Hall of Whispers|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This vast stone hall stretches before you, its arched ceilings looming overhead like the ribs of some great beast, forming a tunnel that disappears into shadows. Columns line either side of the hall, their surfaces worn and cracked, bearing faint carvings barely visible in the dim light. A cool mist clings to the floor, swirling around fragments of stone and fallen debris scattered across the hall. Flickering torches cast a cold, ghostly glow along the walls, illuminating alcoves where statues of forgotten saints and guardians rest, silent witnesses to the passage of time. At the far end, a low set of stairs leads up to a grand archway, where faint, golden light filters through like a whisper of dawn, beckoning you forward.",
        "senses": {
            "feel": "A deep chill permeates the air, sinking into your bones and bringing a sense of weighty silence.",
            "smell": "The scent of damp stone and stale air fills the hall, tinged with a faint hint of ancient decay.",
            "sound": "Soft echoes of your footsteps resonate through the empty hall, accompanied by the distant drip of water somewhere unseen.",
            "taste": "The air tastes cold and metallic, carrying a hint of dust and the remnants of long-extinguished flames.",
        },
        "details": {
            "columns": "The columns line the hall like solemn sentinels, each marked by the wear of centuries, their surfaces rough and adorned with faint carvings of mythical creatures and ancient symbols.",
            "statues": "Stone statues rest within alcoves, their faces weathered and blank, each figure cloaked and gazing outward with eyes that seem almost alive in the shifting torchlight.",
            "golden archway": "The grand archway at the far end of the hall radiates a faint golden glow, its light spilling softly down the steps, as if calling you toward something hidden beyond.",
        },
    },
    (0, 0): {
        "key": "|#565656Emberlyn Crypt - Pillared Sanctum|n",
        "typeclass": "world.xyzgrid.xyzroom.XYZRoom",
        "desc": "This circular sanctum is dominated by towering, intricately carved pillars that rise toward the vaulted ceiling, framing the space with an almost reverential silence. Each pillar is etched with worn symbols and delicate reliefs. Steps lead up to a raised platform at the center, where stone carvings and faint, circular engravings suggest ancient rituals or prayers once performed here. Dim sconces line the walls, their flames steady and cold, casting elongated shadows that dance among the arches and alcoves. Large, sealed urns rest in shadowed corners, and a candelabrum, covered in a thin layer of dust, stands in quiet tribute. The air is dense, thick with the scent of old stone and faint traces of incense, as if the walls themselves remember the sanctity of those who came before.",
        "senses": {
            "feel": "The air is dense and cool, carrying a weight of solemnity that settles heavily on your shoulders.",
            "smell": "A faint scent of stale incense lingers, mingled with the earthy odor of stone and dust.",
            "sound": "The chamber is silent save for the quiet flicker of torches, their flames unwavering in the still air.",
            "taste": "The air has a dry, almost chalky taste, hinting at centuries of silence and reverence.",
        },
        "details": {
            "pillars": "The pillars are grand and intricately carved, each adorned with faded symbols and reliefs depicting unknown figures, their forms worn smooth by the passage of time.",
            "platform": "The raised platform at the center bears faint circular engravings, symbols of an ancient rite, now partially obscured by dust and time, as though marking a place of ritual importance.",
            "urns": "Large, sealed urns rest in the corners, their surfaces thick with dust and age, perhaps containing remnants of offerings left by those who once honored this place.",
        },
    },
}
